services:
  web:
    build: .
    container_name: dwes-web
    volumes:
      - ../.:/var/www/html
    ports:
      - '80:80'

  db:
    image: 'mysql:latest'
    container_name: dwes-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: series
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: dwes-phpmyadmin
    restart: always
    environment:
      PMA_HOST: dwes-db
      PMA_USER: root
    ports:
      - '8000:80'

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: dwes-portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    ports:
      - '9443:9000'

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
  portainer_data:
